name: cfn-nag-action

on: [push]

jobs:
  cloudformation-nag:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: setup & Run
        uses: stelligent/cfn_nag@master
        with:
          input_path: .
          extra_args: --fail-on-warnings --output-format sarif 
          output_path: cfn_nag.sarif
      - name: Archive output
        uses: actions/upload-artifact@v3
        with:
          name: cnf-nag-artifact
          path: ${{ github.workspace }}/cfn_nag.out
