name: cfn-security 

on: [push]

jobs:
  ## all scans
  cfn-security:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: rsahu-swi/cfn-security@master
      with:
        cloudformation_directory: "."
        scanner: "all"
