name: sierra-cfn-scan 

on: [push]

jobs:
  ## all scans
  sierra-cfn-scan:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: rsahu-swi/cfn-security@master
      with:
        cloudformation_directory: "."
        scanner: "all"
